apiVersion: v1
kind: Template
metadata:
  name: ansible-jupyter-kernel
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ansible-jupyter
    name: ansible-jupyter
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: centos 
- apiVersion: image.openshift.io/v1
  kind: ImageStreamTag
  metadata:
    name: centos:7
  tag:
    from:
      kind: DockerImage
      name: centos:7
    importPolicy: {}
    name: "7"
    referencePolicy:
      type: Source
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ansible-jupyter
    name: ansible-jupyter
  spec:
    ports:
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: ansible-jupyter
      deploymentconfig: ansible-jupyter
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ansible-jupyter
    name: ansible-jupyter
  spec:
    replicas: 1
    selector:
      app: ansible-jupyter
      deploymentconfig: ansible-jupyter
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ansible-jupyter
          deploymentconfig: ansible-jupyter
      spec:
        containers:
        - image: '' 
          imagePullPolicy: Always
          name: ansible-jupyter
          ports:
          - containerPort: 8888
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ansible-jupyter
        from:
          kind: ImageStreamTag
          name: ansible-jupyter:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ansible-jupyter
    name: ansible-jupyter
  spec:
    port:
      targetPort: 8888-tcp
    to:
      kind: Service
      name: ansible-jupyter
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ansible-jupyter
    name: ansible-jupyter
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ansible-jupyter:latest
    source:
      contextDir: openshift
      git:
        ref: "${SOURCE_REPOSITORY_REF}" 
        uri: "${SOURCE_REPOSITORY_URL}" 
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:7
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/ansible/ansible-jupyter-kernel
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: master

